apisearch-io/search-server

app.yml
Redis Cluster - disabled
Elasticsearch Cluster - disabled
=> Change default conf - Clusters disabled

Dockerfile
- This will be included in a new image tag
=> Removed newrelic from dockerfile.

composer.lock, docker/server-entrypoint.sh
=> Updated server integration

Console/CommandsConsumer.php, Domain/Token/StaticTokenLocator.php
- Commands consumer output formatted
=> Main Readonly token with 60ms cache

Controller/CreateIndexController.php, Exception/ParsedCreatingIndexException.php, Plugin/Elastica/Domain/ElasticaWrapper.php, Tests/Functional/Http/CreateIndexTest.php
Update for #123.
- Updated response while creating the index which is already established before.
- Updated response code as 201 when the index correctly created.
=> Added creating index response exception parser for elastica wrapper

composer.json, composer.lock, docker/server-entrypoint.sh
- Improved server output
- Favicon is no longer being registered by the server
=> Updated one-bunlde-app deps

Console/CommandsConsumer.php
- When less than 1ms, then <1ms
=> Showing milliseconds

Console/PrintIndicesCommand.php, Controller/GetIndicesController.php, Domain/Query/GetIndices.php, Domain/QueryHandler/GetIndicesHandler.php, Domain/Repository/Repository/IndexRepository.php, Domain/Repository/Repository/Repository.php, Plugin/Elastica/Domain/ElasticaWrapper.php, Plugin/Elastica/Domain/EventRepository/EventElasticaWrapper.php, Plugin/Elastica/Domain/LogRepository/LogElasticaWrapper.php, Plugin/Elastica/Domain/Repository/IndexRepository.php, Plugin/Elastica/Domain/Repository/ItemElasticaWrapper.php, Resources/config/console.yml, Resources/config/controllers.yml, Resources/config/domain.yml, Resources/config/routing.yml, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Repository/AllTests.php, Tests/Functional/Domain/Repository/GetIndicesTest.php, Tests/Functional/HttpFunctionalTest.php, Tests/Functional/ServiceFunctionalTest.php, composer.lock
#125 
- Added command line interface
- Added API endpoint (controller) to the server
- Updated ElasticaWrapper and Elasticsearch Plugin
Tests will be added after finishing the first review.
Requirement: This pr require to merge the [this pr](https://github.com/apisearch-io/php-client/pull/41) and a new release for php-client
=> List all indices

DependencyInjection/CompilerPass/CommandBusCompilerPass.php, Plugin/MetadataFields/Resources/config/repository.yml, Plugin/Redis/Resources/config/domain.yml, Resources/config/controllers.yml, Resources/config/domain.yml, Resources/test/subscribers.yml, app.yml, composer.json, composer.lock
~For now, the tests crashed. I will fix after review the code part. Sorry about that.~
I think we need to remove this `public: true`s from the services. Because only test side using directly `$container->get()` method. Maybe we can find a solution for working the tests without making public the services. I used `controller.service_arguments` tag for the controllers without making public.
=> DeprecationException fix

Plugin/Elastica/Domain/Repository/QueryRepository.php, Tests/Functional/Domain/Repository/SocketRepositoryTest.php, docker/server-pm-entrypoint.sh
- Also, reduced to 3 workers the PPM server
=> Disabled explain in queries

Console/AddTokenCommand.php, Console/CheckHealthCommand.php, Console/CheckIndexCommand.php, Console/CleanEnvironmentCommand.php, Console/CommandWithBusAndGodToken.php, Console/ConfigureEnvironmentCommand.php, Console/ConfigureIndexCommand.php, Console/CreateIndexCommand.php, Console/DeleteIndexCommand.php, Console/DeleteTokenCommand.php, Console/DeleteTokensCommand.php, Console/ExportIndexCommand.php, Console/GenerateBasicTokensCommand.php, Console/ImportIndexCommand.php, Console/PauseConsumersCommand.php, Console/PrintIndicesCommand.php, Console/PrintTokensCommand.php, Console/QueryCommand.php, Console/ResumeConsumersCommand.php, Console/ServerConfigurationCommand.php, Plugin/Elastica/Domain/ItemElasticaWrapper.php, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/Console/AddDeleteTokensCommandTest.php, Tests/Functional/Domain/Repository/GetIndicesTest.php, app.yml, composer.lock
- Using new bundle and php library versions.
- Commands improved
- List indices now is showing metadata and fields
=> Using new lib versions + Index fields

Plugin/Compression/CompressionPluginBundle.php, Plugin/Compression/Domain/Listener/ResponseListener.php, Plugin/Compression/Resources/config/listeners.yml, Plugin/Compression/Tests/Functional/BasicCompressionTest.php, Tests/Functional/CurlFunctionalTest.php, app.yml
=> Added compression plugin

.circleci/config.yml, DependencyInjection/ApisearchServerExtension.php, Domain/QueryHandler/QueryHandler.php, Exception/ExternalResourceException.php, Plugin/RabbitMQ/Console/RabbitMQConsumer.php, Plugin/RabbitMQ/Domain/RabbitMQChannel.php, Plugin/RabbitMQ/Domain/RabbitMQConsumerManager.php, Plugin/RabbitMQ/Domain/RabbitMQTrierTrait.php, Plugin/RabbitMQ/Tests/Functional/AsynchronousCommandsTest.php, Plugin/RabbitMQ/Tests/Functional/ConsumerManagerTest.php, Plugin/RabbitMQ/Tests/Functional/RabbitMQTestTrait.php, Plugin/Redis/Domain/RedisFactory.php, Plugin/Redis/Domain/RedisWrapper.php, Plugin/RedisQueue/Domain/RedisQueueConsumerManager.php, Plugin/RedisQueue/Domain/RedisQueueTrierTrait.php, Plugin/RedisQueue/Tests/Functional/AsynchronousCommandsTest.php, Plugin/RedisQueue/Tests/Functional/ConsumerManagerTest.php, Plugin/RedisQueue/Tests/Functional/RedisQueueTestTrait.php, Tests/Functional/AsynchronousFunctionalTest.php, Tests/Functional/Domain/Repository/AsynchronousCommandNoBundleTest.php, Tests/Functional/Domain/Repository/AsynchronousCommandsTest.php, Tests/Functional/Domain/Repository/MultiqueryTest.php
- RabbitMQ
- Redis
Both consumers and producers (commands / server) should be able to
reconnect to the service as soon as there's some kind of disconection
event.
=> Queues plugins should be able to reconnect lost connections

Controller/Extractor/RequestContentExtractor.php, Controller/Listener/TokenCheckOverHTTP.php, Controller/QueryController.php, Domain/Token/CredentialsTokenValidator.php, Plugin/Elastica/Domain/ItemElasticaWrapper.php, Plugin/Elastica/Domain/Repository/QueryRepository.php, Plugin/Security/Domain/Middleware/RestrictedFieldsMiddleware.php, Plugin/Security/Tests/Functional/BasicSecurityTest.php, Tests/Functional/Domain/Repository/MultiqueryTest.php, Tests/Functional/Domain/Repository/RepositoryPermissionsTest.php, Tests/Functional/Domain/Token/TokenTest.php, composer.lock
- This changes the security on queries and its subqueries
=> Added force index in query

Console/GenerateCrontabCommand.php, Domain/Event/InteractionWasAdded.php, Domain/Middleware/CheckHealthPluginsMiddleware.php, Domain/Model/CrontabLine.php, Domain/Plugin/CrontabMiddleware.php, Domain/Plugin/PluginMiddleware.php, Domain/Plugin/PluginMiddlewareCollector.php, Domain/Query/GetCrontab.php, Domain/QueryHandler/GetCrontabHandler.php, Plugin/Elastica/DependencyInjection/ElasticaPluginConfiguration.php, Plugin/Elastica/Domain/Builder/QueryBuilder.php, Plugin/Elastica/Domain/ItemElasticaWrapper.php, Plugin/Elastica/Domain/Middleware/CheckHealthMiddleware.php, Plugin/Elastica/Domain/Middleware/TransactionElasticaMiddleware.php, Plugin/MostRelevantWords/Domain/Middleware/IndexItemsMiddleware.php, Plugin/RedisMetadataFields/DependencyInjection/RedisMetadataFieldsPluginConfiguration.php, Plugin/RedisMetadataFields/Domain/Middleware/DeleteItemsMiddleware.php, Plugin/RedisMetadataFields/Domain/Middleware/IndexItemsMiddleware.php, Plugin/RedisMetadataFields/Domain/Middleware/QueryMiddleware.php, Plugin/RedisStorage/Domain/Middleware/CheckHealthMiddleware.php, Plugin/Security/Domain/Middleware/RestrictedFieldsMiddleware.php, README.md, Resources/config/console.yml, Resources/config/domain.yml, Tests/Functional/Console/Crontab/FakeCrontabMiddleware.php, Tests/Functional/Console/GenerateCrontabCommandTest.php, Tests/Unit/Domain/Plugin/PluginMiddlewareCollectorTest.php, composer.lock, docker/crontab.sh
- There is a new Query/QueryHandler to collect all crontab lines
- Each plugin can provide custom lines
- There is a new command that collect them all and puts in crontab
- There is a new docker entrypoint that run this command and runs cron in foregrownd
- Refactored method getSubscribedEvents for getSubscribedCommands, as we subscribe commands
not events
- Updated dependencies
=> Adding crontab feature in Apisearch

Controller/Listener/TokenCheckOverHTTP.php, Domain/Token/CredentialsTokenValidator.php, Plugin/StaticTokens/Domain/Token/StaticTokenLocator.php, Plugin/StaticTokens/Tests/Functional/ShortRouteTest.php, Resources/config/routing.yml, composer.lock
- If a token has an specific app_id and a set of indices, by using this endpoint
you will be able to work in a short way
=> Added /v1 short endpoint for specific tokens

DependencyInjection/Env.php, Plugin/DBAL/DBALPluginBundle.php, Plugin/DBAL/DependencyInjection/CompilerPass/ConnectionCompilerPass.php, Plugin/DBAL/DependencyInjection/DBALPluginConfiguration.php, Plugin/DBAL/DependencyInjection/DBALPluginExtension.php, Plugin/DBAL/Tests/Functional/DBALFunctionalTestTrait.php, Plugin/Elastica/DependencyInjection/ElasticaPluginConfiguration.php, composer.json, composer.lock, phpunit.xml
Possible values for DBAL_DRIVER: mysql, sqlite, postgres
```
DBAL_DRIVER=mysql
DBAL_HOST=127.0.0.1
DBAL_PORT=3306
DBAL_USER=root
DBAL_PASSWORD=root
DBAL_DBNAME=apisearch
DBAL_TOKENS_TABLE=tokens
```
=> Using new DBAL configuration builder for plugin

Plugin/Security/DependencyInjection/CompilerPass/ClientCompilerPass.php, Plugin/Security/DependencyInjection/SecurityPluginConfiguration.php, Plugin/Security/DependencyInjection/SecurityPluginExtension.php, Plugin/Security/Resources/config/domain.yml, Plugin/Security/Tests/Functional/SecurityFunctionalTest.php, composer.json, composer.lock
REDIS_HOST
REDIS_PORT
REDIS_DATABASE
REDIS_PASSWORD
=> Added Redis custom loader. Using new env variables

Console/AddTokenCommand.php, Console/GenerateBasicTokensCommand.php, Controller/PutTokenController.php, Domain/Command/PutToken.php, Domain/CommandHandler/PutTokenHandler.php, Domain/Event/TokenWasPut.php, Domain/Repository/AppRepository/TokenRepository.php, Drift/config/services.yml, Plugin/Logstash/Domain/Event/DomainEventSubscriber.php, Plugin/Logstash/Resources/config/domain.yml, Plugin/Security/Tests/Functional/BasicSecurityTest.php, Resources/config/routes.yml, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Repository/TokenQueriesTest.php, Tests/Functional/Domain/Token/TokenTest.php, Tests/Functional/HttpFunctionalTest.php, Tests/Functional/ServiceFunctionalTest.php, Tests/Unit/Domain/Command/AddTokenTest.php, composer.json, composer.lock
- Token id must be part of the resource url
- Token id not necessary in the body
- Using new php-client version
=> Fixed putToken endpoint

.circleci/config.yml, Domain/Repository/AppRepository/InMemoryTokenRepository.php, Domain/Repository/AppRepository/Repository.php, Domain/Repository/AppRepository/TokenRepository.php, Plugin/DBAL/Domain/Middleware/CheckHealthMiddleware.php, Plugin/DBAL/Domain/Token/DBALTokenRepository.php, Plugin/DBAL/Resources/config/domain.yml, Plugin/DBAL/Tests/Functional/DBALFunctionalTestTrait.php, Plugin/DBAL/Tests/Functional/DBALTokenRepositoryTest.php, Plugin/Logstash/Domain/Event/DomainEventSubscriber.php, Plugin/QueryMapper/Domain/MappedTokenLocator.php, Resources/config/services.yml, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/Domain/Token/InMemoryTokenTest.php, Tests/Functional/Domain/Token/TokenTest.php, Tests/Unit/Domain/Repository/AppRepository/InMemoryTokenRepositoryTest.php, composer.json, composer.lock, docker-compose/docker-compose-infra.yml, docker/create-infrastructure.sh, docker/server-entrypoint.sh, phpunit.xml, scripts/run-tests
- Added some tests to cover this case
- Fixed the method name for putting a token
- Added entrypoint without creating infrastructure + possibility to have
both at the same time
sh /server-entrypoint.sh
sh /create-infrastructure.sh /server-entrypoint.sh
=> Fixed tokens reload on wakeup

.circleci/config.yml, .circleci/scripts/run-domain-tests, .dockerignore, Plugin/Elasticsearch/Tests/CurlRepositoryTest.php, Plugin/Elasticsearch/Tests/QueryBadFormatTest.php, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Token/TokenTest.php, composer.json, composer.lock, phpunit.xml
- Curl tests use custom and async server execution
- Improved circleci to work with preloaded images
- Infrastructure tests (plugins) are being fired directly from the main
docker image
- Domain tests are being passed with custom apisearch image
=> Improved tests performance

Tests/Functional/Domain/Repository/AggregationsTest.php, Tests/Functional/Domain/Repository/MultiqueryTest.php, composer.json, composer.lock
- Introduced fix for 0 treatment
=> Using new library version for ranges

Console/PrintUsageCommand.php, Controller/CreateIndexController.php, Controller/GetUsageController.php, Domain/Listener/UsagePusher.php, Domain/Query/GetUsage.php, Domain/QueryHandler/GetUsageHandler.php, Domain/Repository/UsageRepository/InMemoryUsageRepository.php, Domain/Repository/UsageRepository/UsageRepository.php, Drift/config/services.yml, Plugin/DBAL/Domain/UsageRepository/ChunkUsageRepository.php, Plugin/DBAL/Domain/UsageRepository/DBALUsageRepository.php, Plugin/DBAL/Tests/Functional/ChunkUsageRepositoryTest.php, Plugin/DBAL/Tests/Functional/DBALUsageRepositoryTest.php, Resources/config/routes.yml, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Repository/CurlUsageRepositoryTest.php, Tests/Functional/Domain/Repository/ServiceUsageRepositoryTest.php, Tests/Functional/Domain/Repository/UsageRepositoryTest.php, Tests/Functional/ServiceFunctionalTest.php, Tests/Unit/Domain/Repository/UsageRepository/UsageRepositoryTest.php, phpunit.xml
- Added improved HTTP endpoint
- Added optional parameters: indexUUID, from, to, event
- Added endpoints for app and index usages
- Added endpoints for total values or "per-day" values
- Added more tests coverage, including HTTP ones
- Improved InMemoryUsageRepository (lines are stored in cumulative way)
=> Improved usage feature

Domain/Repository/UsageRepository/InMemoryUsageRepository.php, Plugin/DBAL/Domain/UsageRepository/DBALUsageRepository.php, Plugin/DBAL/Tests/Functional/DBALUsageRepositoryTest.php, Tests/Functional/Domain/Repository/UsageRepositoryTest.php, Tests/Unit/Domain/Repository/UsageRepository/UsageRepositoryTest.php
- This format improves the readibility from front applications
=> Using usage datetime format - Ymd -

ApisearchPluginsBundle.php, Domain/Middleware/GetIndicesMetadataMiddleware.php, Domain/Repository/AppRepository/InMemoryTokenRepository.php, Domain/Repository/InMemoryRepository.php, Domain/Repository/MetadataRepository/InMemoryMetadataRepository.php, Domain/Repository/ResetableRepository.php, Domain/Repository/UsageRepository/InMemoryUsageRepository.php, Plugin/Testing/Controller/ResetInMemoryRepositoriesController.php, Plugin/Testing/Resources/config/domain.yml, Plugin/Testing/Resources/config/routes.yml, Plugin/Testing/Resources/config/testing_routes.yml, Plugin/Testing/TestingPluginBundle.php, Plugin/Testing/Tests/ResetInMemoryRepositoriesControllerTest.php, Plugin/Testing/Tests/TestingPluginFunctionalTest.php, Resources/config/services.yml, Tests/Functional/Domain/Token/InMemoryTokenTest.php
- Usable for hard reset of the system when using local in_memory
repositories
=> Added small testing plugin

Domain/Repository/AppRepository/TokenRepository.php, Domain/Token/StaticTokenLocator.php, Plugin/Admin/Controller/GetTokensController.php, Plugin/Admin/Domain/ImperativeEvents.php, Plugin/Admin/Resources/config/admin_routes.yml, Plugin/Admin/Tests/GetTokensTest.php, Plugin/Security/Domain/Middleware/RestrictedOriginsMiddleware.php, Tests/Unit/Domain/Repository/AppRepository/InMemoryTokenRepositoryTest.php, composer.lock
- Added flush metadata to imperative events list for manually dispatch event from admin plugin.
- Added get all tokens in admin plugin. Some changes on token repository.
=> Changes on admin

DependencyInjection/CompilerPass/EventBusCompilerPass.php, Domain/Repository/UsageRepository/InMemoryUsageRepository.php, Plugin/Admin/Controller/ControllerWithQueryBusAsGod.php, Plugin/Admin/Controller/GetAppsController.php, Plugin/Admin/Controller/GetTokensController.php, Plugin/Admin/Controller/GetUsageController.php, Plugin/Admin/Domain/ImperativeEvents.php, Plugin/Admin/Resources/config/admin_routes.yml, Plugin/Admin/Tests/AdminPluginFunctionalTest.php, Plugin/Admin/Tests/GetUsageTest.php, Plugin/DBAL/Domain/UsageRepository/DBALUsageRepository.php, Tests/Unit/Domain/Repository/UsageRepository/UsageRepositoryTest.php
- Changed the repository. Can be called with appUUID = *
=> Added get cluster usage for admin bundle

Controller/QueryCORSController.php, Domain/Query/GetCORSPermissions.php, Plugin/Security/Domain/Middleware/RestrictedOriginsMiddleware.php, Plugin/Security/Domain/OriginMatcherTrait.php, Plugin/Security/Tests/Functional/CORSFunctionalTest.php, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/HttpFunctionalTest.php, Tests/Functional/ServiceFunctionalTest.php
- Using `blocked_ips` metadata value
=> Added IP blocking into security plugin

DependencyInjection/CompilerPass/EventBusCompilerPass.php, composer.json, composer.lock
- If the event is not listed, the event is not dispatched
=> Using new event-bus router

Console/ConfigureIndexCommand.php, Controller/ConfigureIndexController.php, Domain/Command/ConfigureIndex.php, Domain/CommandHandler/ConfigureIndexHandler.php, Domain/Middleware/ComplexFields/ResetOrDeleteIndexComplexFieldsMiddleware.php, Plugin/Elasticsearch/Domain/ElasticaWrapper.php, Plugin/Security/Tests/Functional/RestrictedCORSOriginsMiddlewareTest.php, Resources/config/command_bus.yml, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Repository/ComplexFieldsTest.php, Tests/Functional/Domain/Repository/IndexConfigurationTest.php, Tests/Functional/Domain/Repository/IndicesTest.php, Tests/Functional/Domain/Repository/MetadataRepositoryTest.php, Tests/Functional/Domain/Repository/RepositoryResetTest.php, Tests/Functional/HttpFunctionalTest.php, Tests/Functional/ServiceFunctionalTest.php, composer.json, composer.lock
- Complex fields are reset/deleted on index deletion/reset
=> Index can be forced to reindex when configuring it

Plugin/Elasticsearch/Adapter/AsyncClient.php, Plugin/Elasticsearch/Tests/ExceptionMessagesTest.php, Tests/Functional/Domain/Repository/AllSearchTests.php, Tests/Functional/Domain/Repository/ExceptionMessagesTest.php, Tests/Functional/Domain/Repository/FieldTypesTest.php
- Tested field type error exception message
- Test field types
=> Fixed exception message when comes from elasticsearch

Domain/Event/ItemsWereDeleted.php, Domain/Event/ItemsWereIndexed.php, Plugin/Logstash/Tests/Functional/BasicUsageTest.php, Plugin/Logstash/Tests/Functional/LogstashFunctionalTest.php, Plugin/Security/Tests/Functional/RestrictedCORSOriginsMiddlewareTest.php, composer.json, composer.lock, docker/create-infrastructure.sh
=> Covered subdomains on origin security

Controller/PostClickController.php, Domain/Command/PostClick.php, Domain/CommandHandler/PostClickHandler.php, Exception/InvalidClickException.php, Plugin/Elasticsearch/Domain/Parser/IndexParser.php, Plugin/Elasticsearch/Domain/Repository/QueryRepository.php, Plugin/Elasticsearch/Tests/Domain/Parser/IndexParserTest.php, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Repository/AllSearchTests.php, Tests/Functional/Domain/Repository/InteractionRepository/InteractionRepositoryTest.php, Tests/Functional/Domain/Repository/QueryNestedTest.php, Tests/Functional/Domain/Repository/QueryTest.php, Tests/Functional/HttpFunctionalTest.php, Tests/Functional/ServiceFunctionalTest.php, composer.json, composer.lock
- Fixed a small issue in clicks (when user_id is not passed, we will use
the IP as a simple id. If this is empty, then error 400)
=> Added app and index uuid in result items

Domain/Repository/UsageRepository/EmptyUsageRepository.php, Domain/Repository/UsageRepository/InMemoryUsageRepository.php, Domain/Repository/UsageRepository/UsageRepository.php, Plugin/Admin/Controller/ControllerWithCommandBusAsGod.php, Plugin/Admin/Controller/DispatchImperativeEventController.php, Plugin/Admin/Controller/GetAppsController.php, Plugin/Admin/Controller/GetTokensController.php, Plugin/Admin/Controller/OptimizeUsageLinesController.php, Plugin/Admin/Domain/Command/OptimizeUsageLines.php, Plugin/Admin/Domain/CommandHandler/OptimizeUsageLinesHandler.php, Plugin/Admin/Resources/config/admin_routes.yml, Plugin/Admin/Resources/config/domain.yml, Plugin/Admin/Tests/OptimizeUsageLinesTest.php, Plugin/DBAL/Domain/UsageRepository/ChunkUsageRepository.php, Plugin/DBAL/Domain/UsageRepository/DBALUsageRepository.php, Plugin/DBAL/Tests/Unit/ChunkUsageRepositoryTest.php, Plugin/DBAL/Tests/Unit/DBALUsageRepositoryTest.php, Tests/Unit/Domain/Repository/UsageRepository/InMemoryUsageRepositoryTest.php, Tests/Unit/Domain/Repository/UsageRepository/UsageRepositoryTest.php
- DateTime from and to has to be defined
- A new endpoint has added /admin/usages/optimize. Expects these two
values as paremeters with format "Ymd"
=> Added UsageLines optimization feature

Controller/Listener/TokenCheckOverHTTP.php, Domain/Token/CredentialsTokenValidator.php, Domain/Token/TokenManager.php, Domain/Token/TokenValidator.php, Plugin/Security/Domain/Token/HttpReferrersTokenValidator.php, Plugin/Security/Domain/Token/RequestsLimitTokenValidator.php, Plugin/Security/Domain/Token/SecondsValidTokenValidator.php, Resources/config/routes.yml, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Token/TokenTest.php
- tokens
- indices
- catalog
- usage
- query
- interactions
- click
- searches
- metrics
Endpoints can be accesses as well by their full and redyced name
- apisearch_v1_get_searches
- v1_get_searches
=> Added routes tags for permissions

Controller/PostClickController.php, Domain/Command/PostClick.php, Domain/CommandHandler/PostClickHandler.php, Domain/Repository/InteractionRepository/InMemoryInteractionRepository.php, Domain/Repository/InteractionRepository/Interaction.php, Domain/Repository/InteractionRepository/InteractionRepository.php, Domain/Repository/InteractionRepository/TestableInteractionRepository.php, Plugin/DBAL/Domain/InteractionRepository/ChunkInteractionRepository.php, Plugin/DBAL/Domain/InteractionRepository/DBALInteractionRepository.php, Plugin/DBAL/Tests/Functional/DBALFunctionalTestTrait.php, Plugin/DBAL/Tests/Functional/DBALInteractionRepositoryTest.php, Plugin/DBAL/Tests/Unit/DBALInteractionRepositoryTest.php, Resources/test/services.yml, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/CurlFunctionalTest.php, Tests/Functional/Domain/Repository/InteractionRepository/InteractionRepositoryTest.php, Tests/Functional/Http/MetricsTest.php, Tests/Functional/HttpFunctionalTest.php, Tests/Functional/ServiceFunctionalTest.php, Tests/Unit/Domain/Repository/InteractionRepository/InteractionRepositoryTest.php, docker-compose/mysql/interactions.sql
- An interaction with an item needs a position. By default, 0
=> Added position to interactions

Controller/ExportIndexController.php, Controller/ImportIndexController.php, Controller/PostClickController.php, Plugin/Admin/Controller/OptimizeUsageLinesController.php, Plugin/Elasticsearch/Adapter/AsyncClient.php, Plugin/Testing/Controller/ResetInMemoryRepositoriesController.php, Resources/config/services.yml, Tests/Functional/Domain/Repository/ExportTest.php, composer.json, composer.lock
- Going to more stable dependencies
- Fixing ReactPHP Http v1.0.0 BC Breaks
=> Update of dependencies

.circleci/config.yml, phpunit.xml
- Deleted mysql image from circleci
=> Added sqlite for testing

.gitattributes, Controller/ControllerWithCommandBusAsGod.php, Controller/ControllerWithQueryBusAsGod.php, Domain/Repository/MetadataRepository/MetadataRepository.php, Plugin/Admin/Controller/GetAppsController.php, Plugin/Admin/Controller/GetTokensController.php, Plugin/Admin/Controller/GetUsageController.php, Plugin/Admin/Controller/OptimizeUsageLinesController.php, Plugin/Admin/Tests/AdminPluginFunctionalTest.php, Plugin/DBAL/DependencyInjection/CompilerPass/ConnectionCompilerPass.php, Plugin/DBAL/Domain/AppRepository/DBALConfigRepository.php, Plugin/DBAL/Domain/AppRepository/DBALTokenRepository.php, Plugin/DBAL/Domain/InteractionRepository/DBALInteractionRepository.php, Plugin/DBAL/Domain/MetadataRepository/DBALMetadataRepository.php, Plugin/DBAL/Domain/Middleware/CheckHealthMiddleware.php, Plugin/DBAL/Domain/SearchesRepository/DBALSearchesRepository.php, Plugin/DBAL/Domain/UsageRepository/ChunkUsageRepository.php, Plugin/DBAL/Domain/UsageRepository/DBALUsageRepository.php, Plugin/DBAL/Resources/config/domain.yml, Plugin/DBAL/Tests/Functional/DBALFunctionalTestTrait.php, Plugin/DBAL/Tests/Functional/DBALTokenRepositoryTest.php, Plugin/DBAL/Tests/Unit/ChunkUsageRepositoryTest.php, composer.json, composer.lock
- Using new DriftPHP kernel feature that allows to create loop interval
service calls as configuration
- Made a controller abstraction
- Changed DBAL named injection to allow multiple DBAL connection
injections
=> Added some modifications

Plugin/Elasticsearch/Domain/Builder/QueryBuilder.php, Tests/Functional/Domain/Repository/QueryTest.php, docker-compose/docker-compose-elasticsearch.yml, docker-compose/docker-compose-infra.yml
=> Min score only applied when has query

Exception/ParsedResourceNotAvailableException.php, Plugin/DBAL/Domain/InteractionRepository/ChunkInteractionRepository.php, Plugin/DBAL/Domain/Middleware/CheckHealthMiddleware.php, Plugin/DBAL/Domain/SearchesRepository/ChunkSearchesRepository.php, Plugin/DBAL/Domain/UsageRepository/ChunkUsageRepository.php, Plugin/DBAL/Tests/Functional/HealthTest.php, Plugin/DBAL/Tests/Functional/ShutdownInteractionRepositoryTest.php, Plugin/DBAL/Tests/Functional/ShutdownSearchesRepositoryTest.php, Plugin/DBAL/Tests/Functional/ShutdownUsageRepositoryTest.php, Plugin/Elasticsearch/Domain/Middleware/CheckHealthMiddleware.php, Plugin/Fastly/Listener/QueryHeaders.php, Plugin/Logstash/Domain/Event/DomainEventSubscriber.php, composer.json, composer.lock
- When the server is shutted down, chunk repositories flush their local
items to master
=> Updated deps and implemented shutdown event listeners

Drift/config/services.yml, docker/create-infrastructure.sh, docker/crontab.sh, docker/server-entrypoint.sh
- Deleted entrypoints cache:clear
=> Preloaded bus services

Domain/Repository/AppRepository/InMemoryTokenRepository.php, Plugin/DBAL/Domain/Encrypter/OpenSSLEncrypter.php, docker-hub/docker-build.sh
- Added docker build and push script with commit as version
=> Encrypted data is saved as utf8

Domain/Command/DeleteItems.php, Domain/Model/ServerQuery.php, Domain/Query/GetSimilarItems.php, Domain/QueryHandler/GetSearchesHandler.php, Domain/QueryHandler/GetSimilarItemsHandler.php, Domain/QueryHandler/GetTokensHandler.php, Domain/Repository/DiskRepository.php, Domain/Repository/InMemoryRepository.php, Domain/Repository/Repository/QueryRepository.php, Domain/Repository/Repository/Repository.php, Http/GetRecommendedItemsController.php, Http/GetSimilarItemsController.php, Http/RequestAccessor.php, Plugin/Elasticsearch/Domain/AppRepository/IndexRepository.php, Plugin/Elasticsearch/Domain/Builder/QueryBuilder.php, Plugin/Elasticsearch/Domain/Repository/QueryRepository.php, Plugin/Elasticsearch/Tests/SpecificScenarios/GetSimilarItems.php, Plugin/Elasticsearch/Tests/SpecificScenarios/SpecificScenariosTest.php, Resources/config/routes.yml, composer.json, composer.lock
- Improved distribution of routes alias
=> First implementation of more-like-this

Domain/Command/ConfigureIndex.php, Domain/Command/CreateIndex.php, Domain/Command/DeleteToken.php, Domain/Command/UpdateItems.php, Domain/Now.php, Domain/Query/ExportIndex.php, Domain/Query/GetCORSPermissions.php, Domain/Query/GetCrontab.php, Domain/Query/GetInteractions.php, Domain/Query/GetRecommendedItems.php, Domain/Query/GetSearches.php, Domain/Query/GetTopInteractions.php, Domain/Query/GetTopSearches.php, Domain/Query/GetUsage.php, Domain/QueryHandler/GetRecommendedItemsHandler.php, Domain/QueryHandler/GetTopInteractionsHandler.php, Domain/QueryHandler/GetTopSearchesHandler.php, Domain/QueryHandler/GetUsageHandler.php, Domain/WithAppRepository.php, Domain/WithConfigRepositoryAppRepositoryAndEventPublisher.php, Domain/WithEventBus.php, Domain/WithRepository.php, Domain/WithRepositoryAndEventPublisher.php, Http/GetRecommendedItemsController.php, Plugin/Elasticsearch/Tests/SpecificScenarios/GetSimilarItems.php, Resources/config/routes.yml, Tests/Functional/Http/GetRecommendedItemsTest.php, openapi.yml
- Does nothing, but return random items. Ready for be used in plugins
- Added openapi endpoints for recommendation + similar
- Improved some code for PHP7.4
=> Added fake recommendation endpoint

Plugin/Campaign/Domain/CampaignApplicator.php, Plugin/Campaign/Domain/Model/Campaign.php, Plugin/Campaign/Domain/Model/CampaignModifiers.php, Plugin/Campaign/Tests/Functional/Domain/CampaignScenariosTest.php, Plugin/Campaign/Tests/Unit/Domain/MatcherTest.php, Plugin/Campaign/Tests/Unit/Domain/Model/CampaignTest.php, Tests/Functional/Domain/Repository/GetIndicesTest.php
- A campaign can setup the min_score when is applied.
- The last applied, the last is used
=> Added special query configurations inside Campaign

Domain/Exception/ParsedCreatingIndexException.php, Plugin/Elasticsearch/Domain/ElasticaWrapper.php, Tests/Functional/Domain/Repository/FieldTypesTest.php, Tests/Functional/Domain/Repository/SynonymsTest.php, Tests/items.yml
- Using keyword tokanizer to allow synonyms as filter
=> Changed exact_matching_metadata to work with synonyms

Domain/Middleware/DefaultQueryValuesMiddleware.php, Plugin/Elasticsearch/Domain/Repository/QueryRepository.php, Tests/Functional/Domain/Repository/ExactMatchingMetadataTest.php, composer.lock
- If it's set (by default false), exact matching metadata will match
exclusively. This means that if it matches this field, it will **ONLY**
look for inside this field.
- Updated dependencies
=> Added query metadata for exclusive_exact_matching_metadata

Domain/Middleware/CheckIndexAvailabilityMiddleware.php, Domain/Middleware/CompleteItemsOnIndexMiddleware.php, Plugin/Elasticsearch/Domain/Builder/QueryBuilder.php, Plugin/Elasticsearch/Domain/Builder/ResultBuilder.php, Plugin/Elasticsearch/Domain/ElasticaWrapper.php, Plugin/Elasticsearch/Domain/Repository/ItemRepository.php, Plugin/Elasticsearch/Domain/Repository/QueryRepository.php, Resources/config/command_bus.yml, Tests/Functional/Domain/Repository/ExactMatchingMetadataTest.php, Tests/items.yml
- Created strategy for real-time filtering when an
exact_matching_metadata element matches. Can work with many elements at
the same time.
=> Added progressive exact-matching-metadata

Plugin/Elasticsearch/Domain/Builder/QueryBuilder.php, Tests/Functional/Domain/Repository/UniverseFilterTest.php, Tests/Unit/Domain/Plugin/PluginMiddlewareCollectorTest.php, composer.json, composer.lock
- ["A..B"] will filter from A to B, including A and excluding B
- ["A..B]"] will, instead, include B
=> Added small trick for inclusive ranges

Http/Listener/TokenCacheOverHTTP.php, Tests/Functional/ApisearchServerBundleFunctionalTest.php, Tests/Functional/Http/CacheTest.php
- Added tests
- Changed server response header to an Apisearch / DriftPHP new one
=> Fixed http cache control

Plugin/Elasticsearch/Domain/Repository/QueryRepository.php, Tests/Functional/Domain/Repository/ExactMatchingMetadataTest.php, Tests/items.yml
- Always take the largest match
=> Improved behavior when there are collisions between searches
